-- 1단계: 기본 데이터 확인
SELECT 
    INF.OCR_DOC_NO,
    INF.CTRL_YR,
    INF.INST_CD,
    INF.PRDT_CD,
    INF.CTRL_NO,
    INF.DOC_TP_CD,
    RSLT.OCR_RSLT_NO,
    RSLT.OCR_CNTS IS NOT NULL AS HAS_OCR_CNTS,
    LENGTH(RSLT.OCR_CNTS::TEXT) AS OCR_CNTS_LENGTH
FROM RFDB.OCR_DOC_INF INF
LEFT JOIN RFDB.OCR_DOC_RSLT RSLT 
    ON RSLT.OCR_DOC_NO = INF.OCR_DOC_NO
WHERE INF.CTRL_YR = '24'  -- 실제 값으로 변경
    AND INF.INST_CD = '01'  -- 실제 값으로 변경
    AND INF.PRDT_CD = '820'  -- 실제 값으로 변경
    AND INF.CTRL_NO = '000001'  -- 실제 값으로 변경
LIMIT 5;

-- 2단계: 디코딩 확인
SELECT 
    INF.OCR_DOC_NO,
    PKG_PGCRYPTO$DECRYPT(RSLT.OCR_CNTS) AS DECRYPTED_CNTS,
    LENGTH(PKG_PGCRYPTO$DECRYPT(RSLT.OCR_CNTS)::TEXT) AS DECRYPTED_LENGTH
FROM RFDB.OCR_DOC_INF INF
LEFT JOIN RFDB.OCR_DOC_RSLT RSLT 
    ON RSLT.OCR_DOC_NO = INF.OCR_DOC_NO
WHERE INF.CTRL_YR = '24'
    AND INF.INST_CD = '01'
    AND INF.PRDT_CD = '820'
    AND INF.CTRL_NO = '000001'
    AND RSLT.OCR_CNTS IS NOT NULL
LIMIT 1;

-- 3단계: JSON 파싱 확인
SELECT 
    (JSON_EACH_TEXT(PKG_PGCRYPTO$DECRYPT(RSLT.OCR_CNTS)::JSON)).KEY AS ITEM_CD,
    (JSON_EACH_TEXT(PKG_PGCRYPTO$DECRYPT(RSLT.OCR_CNTS)::JSON)).VALUE AS ITEM_VALUE
FROM RFDB.OCR_DOC_INF INF
LEFT JOIN RFDB.OCR_DOC_RSLT RSLT 
    ON RSLT.OCR_DOC_NO = INF.OCR_DOC_NO
WHERE INF.CTRL_YR = '24'
    AND INF.INST_CD = '01'
    AND INF.PRDT_CD = '820'
    AND INF.CTRL_NO = '000001'
    AND RSLT.OCR_CNTS IS NOT NULL
LIMIT 10;

-- 4단계: C_OCR_DOC_ITEM 테이블 확인
SELECT 
    INST_CD,
    PRDT_CD,
    ITEM_CD,
    ITEM_NM,
    USE_YN
FROM RFDB.C_OCR_DOC_ITEM
WHERE INST_CD = '01'
    AND PRDT_CD = '820'
    AND USE_YN = 'Y'
ORDER BY ITEM_ODR
LIMIT 10;

-- 5단계: 전체 쿼리 간단 버전
WITH base_doc AS (
    SELECT 
        INF.INST_CD,
        INF.PRDT_CD,
        PKG_PGCRYPTO$DECRYPT(RSLT.OCR_CNTS) AS OCR_CNTS
    FROM RFDB.OCR_DOC_INF INF
    LEFT JOIN RFDB.OCR_DOC_RSLT RSLT 
        ON RSLT.OCR_DOC_NO = INF.OCR_DOC_NO
    WHERE INF.CTRL_YR = '24'
        AND INF.INST_CD = '01'
        AND INF.PRDT_CD = '820'
        AND INF.CTRL_NO = '000001'
    LIMIT 1
),
json_parsed AS (
    SELECT 
        (JSON_EACH_TEXT(OCR_CNTS::JSON)).KEY AS ITEM_CD,
        (JSON_EACH_TEXT(OCR_CNTS::JSON)).VALUE AS ITEM_VALUE,
        INST_CD,
        PRDT_CD
    FROM base_doc
    WHERE OCR_CNTS IS NOT NULL
)
SELECT 
    jp.ITEM_CD,
    jp.ITEM_VALUE,
    codi.ITEM_NM
FROM json_parsed jp
LEFT JOIN RFDB.C_OCR_DOC_ITEM codi 
    ON codi.ITEM_CD = jp.ITEM_CD
    AND codi.INST_CD = jp.INST_CD
    AND codi.PRDT_CD = jp.PRDT_CD
    AND codi.USE_YN = 'Y'
LIMIT 10;
